### ISSUE TITLE
Website translation structure proposal

### ISSUE THREAD

**Issue by davedbase** [solidjs/solid-site#116]
Hi folks, I'm looking for some advice on setting up structure for translate the whole Solid Site. Here are a few options I've come up with:

`Option 1` - Use JSON files to outline copy throughout the pages then use solid-i18n to manage lang switching.

`Option 2` - Use a different format like TOML or YAML because it's easier to write than JSON. Convert them to JSON and use solid-i18n. Example of TOML:

```toml
hero = "A declarative, efficient and flexible JavaScript library for building user interfaces."
sub_hero = "Solid is a purely reactive library. It was designed from the groun up with a reactive core. It's influenced by reactive principles developed by previous libraries."

[features.performant]
img = "assets/icons/performant.svg"
title = "Performant"
description = "Consistently tops recognized UI speed and memory utilization benchmarks."

[features.powerful]
img = "assets/icons/powerful.svg"
title = "Powerful"
description = "Composable reactive primitives married with the flexibility of JSX."

[features.pragmatic]
img = "assets/icons/pragmatic.svg"
title = "Pragmatic"
description = "A sensible and tailored API makes developing fun and simple."

[features.productive]
img = "assets/icons/productive.svg"
title = "Productive"
description = "Ergonomics and familiarity make building simple or complex things a breeze."

[quickfeatures.stars]
title = "9.5k+"
subtitle = "Github Stars"
link = "https://star-history.t9t.io/#solidjs/solid"

[quickfeatures.years]
title = "5+ years"
subtitle = "In development"

[quickfeatures.typescript]
title = "TypeScript"
subtitle = "Support"

[quickfeatures.rated]
title = "Top Rated"
subtitle = "In performance"
```

`Option 3` - Find a way to support MDX on the site and manage translations in Markdown and write Solid JSX components into the file as needed.

Other suggestions are more than welcomed.
